import{S as y,A as h}from"./assets/vendor-d52af3f3.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const u=[{title:"Wallet Webservice",image:"./img/my-projects/manager-finance.jpg",techStack:"React, JavaScript, Node JS, Git",link:"https://github.com/kononova1986/project-15",alt:"Wallet Webservice Project"},{title:"Green harvest webservice",image:"./img/my-projects/vegetables.jpg",techStack:"React, JavaScript, Node JS, Git",link:"https://github.com/kononova1986/project-15",alt:"Green harvest"},{title:"English Exellence webservice",image:"./img/my-projects/discover.jpg",techStack:"React, JavaScript, Node JS, Git",link:"https://github.com/kononova1986/project-15",alt:"English Exellence"},{title:"Transform your webservice",image:"./img/my-projects/transform-your.jpg",techStack:"React, JavaScript, Node JS, Git",link:"https://github.com/kononova1986/project-15",alt:"Transform your"},{title:"Ukraine traditions webservice",image:"./img/my-projects/traditions-ukraine.jpg",techStack:"React, JavaScript, Node JS, Git",link:"https://github.com/kononova1986/project-15",alt:"Ukraine traditions"},{title:"Stay Healthy webservice",image:"./img/my-projects/get-body.jpg",techStack:"React, JavaScript, Node JS, Git",link:"https://github.com/kononova1986/project-15",alt:"Stay Healthy"},{title:"Mimino webservice",image:"./img/my-projects/mimino.jpg",techStack:"React, JavaScript, Node JS, Git",link:"https://github.com/kononova1986/project-15",alt:"Mimino"},{title:"Transformation with a Touch of the Brush webservice",image:"./img/my-projects/brand.jpg",techStack:"React, JavaScript, Node JS, Git",link:"https://github.com/kononova1986/project-15",alt:""},{title:"Fresh harvest box webservice",image:"./img/my-projects/fresh.jpg",techStack:"React, JavaScript, Node JS, Git",link:"https://github.com/kononova1986/project-15",alt:"Fresh harvest box"},{title:"Transform your business webservice",image:"./img/my-projects/turn-your.jpg",techStack:"React, JavaScript, Node JS, Git",link:"https://github.com/kononova1986/project-15",alt:"Transform your business"}];let a=0;const d=3;function v(){const e=document.querySelector(".project-list"),n=u.slice(a,a+d).map(({image:s,alt:t,techStack:r,title:i,link:f})=>`
            <li class="project-item">
                <img src="${s}" alt="${t}" class="project-image">
                <div class="project-content">
                    <p class="project-tech">${r}</p>
                    <div class="project-name-btn">
                        <h3 class="project-name">${i}</h3>
                        <div class="centered">
                            <button type="button" class="project-button">
                                <a href="${f}" class="project-link" target="_blank">VISIT
                                    <svg class="project-icon">
                                        <use href="./img/symbol-defs.svg#icon-arrow"></use>
                                    </svg>
                                </a>
                            </button>
                        </div>
                    </div>
                </div>
            </li>
            `).join("");e.innerHTML+=n,a+=d,a>=u.length&&(document.querySelector(".load-more").style.display="none")}document.querySelector(".load-more").addEventListener("click",v);v();const b=document.querySelector(".backdrop-menu-list"),S=document.querySelector(".menu-btn"),k=document.querySelector(".menu-backdrop"),j=document.querySelector(".close-modal-btn ");function l(){k.classList.toggle("is-open")}S.addEventListener("click",l);j.addEventListener("click",l);b.addEventListener("click",e=>{e.target&&l()});const w=document.querySelector(".swiper-button-next"),E=document.querySelector(".swiper-button-prev");async function L(){try{const e=await fetch("https://portfolio-js.b.goit.study/api/reviews");if(!e.ok)throw new Error(`HTTP error! Status: ${e.status}`);return await e.json()}catch(e){return alert("Fetch error: "+e.message),console.error("Fetch error:",e),null}}function q(){new y(".swiper-container",{slidesPerView:1,slidesPerGroup:1,loop:!1,navigation:{nextEl:w,prevEl:E},keyboard:{enabled:!0,onlyInViewport:!1},mousewheel:!0,breakpoints:{768:{slidesPerView:1,slidesPerGroup:1,spaceBetween:32,slideWidth:704},1280:{slidesPerView:2,slidesPerGroup:1,spaceBetween:32,slideWidth:592}},on:{reachEnd:function(){document.querySelector(".swiper-button-next").classList.add("disabled")},reachBeginning:function(){document.querySelector(".swiper-button-prev").classList.add("disabled")},fromEdge:function(){document.querySelector(".swiper-button-next").classList.remove("disabled"),document.querySelector(".swiper-button-prev").classList.remove("disabled")}}})}function J(e){return`<li class="swiper-slide review">
    <p class="review-text">${e.review}</p>
    <div class="swiper-img-container">
      <img class="reviews-img" src="${e.avatar_url}" alt="Avatar">
      <h3 class="name">${e.author}</h3>
    </div>
  </li>`}async function x(e,o){const n=document.querySelector("#reviews-list");if(!n){console.error("Element #reviews-list not found");return}const s=await L();if(!s){n.innerHTML="Not found";return}const t=s.map(r=>o(r)).join("");n.innerHTML=t,e()}x(q,J);const p=document.querySelector(".form-work-togezer"),c=document.querySelector(".footer-modal-background"),P=document.querySelector(".footer-modal-btn"),G=document.querySelector(".input-work-togezer"),M=document.querySelector(".textarea-work-togezer"),m=document.querySelectorAll(".error-message")[0],g=document.querySelectorAll(".error-message")[1];c.style.display="none";p.addEventListener("submit",function(e){e.preventDefault();const o=G.value.trim(),n=M.value.trim();if(N(o))m.style.display="none";else{m.style.display="block";return}if(n===""){g.style.display="block";return}else g.style.display="none";c.style.display="flex",p.reset()});P.addEventListener("click",function(){c.style.display="none"});document.addEventListener("keydown",function(e){e.key==="Escape"&&(c.style.display="none")});c.addEventListener("click",function(e){e.target===c&&(c.style.display="none")});function N(e){return/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)}document.addEventListener("DOMContentLoaded",function(){var e={duration:600,ariaEnabled:!0,collapse:!0,showMultiple:!1,openOnInit:[0],elementClass:"accordion-item",triggerClass:"list-title-box",panelClass:"accordion-text",activeClass:"active",beforeOpen:function(o){console.log("Before opening:",o)},onOpen:function(o){console.log("Opened:",o)},beforeClose:function(o){console.log("Before closing:",o)},onClose:function(o){console.log("Closed:",o)}};new h(".accordion",e),document.querySelectorAll(".accordion-item .list-title-box").forEach(function(o){o.addEventListener("click",function(){var n=o.closest(".accordion-item"),s=n.classList.contains("active");document.querySelectorAll(".accordion-item").forEach(function(t){t.classList.remove("active")}),s||n.classList.add("active")})})});
//# sourceMappingURL=commonHelpers.js.map
